# Generated by Django 3.2.7 on 2021-09-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=95)),
                ('categories', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=189)),
                ('country', models.CharField(max_length=56)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=200)),
                ('postalCode', models.CharField(max_length=10)),
                ('province', models.CharField(max_length=2)),
                ('websites', models.CharField(max_length=2083)),
            ],
        ),
    ]
