# Generated by Django 3.2.7 on 2021-09-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20210920_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='categories',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
